#!/bin/bash

echo "------------------------------"
echo "Running Rust module"
echo "------------------------------"
echo ""

if [[ -z "${SMU_ZSH_DIR+x}" ]]; then
    echo "It looks like you are not using the set-me-up terminal module."
    echo "Please follow the rbenv instructions above (generated by the command 'rbenv init') to complete the installation."
    read -n 1 -s -r -p "Press any key to continue."
    echo ""
fi

echo "------------------------------"
echo "Installing Rust with Cargo"

if ! command -v "cargo" &>/dev/null; then
    curl https://sh.rustup.rs -sSf | sh
fi

echo "------------------------------"
echo "Installing Cargo packages"

cargo install topgrade
