#!/bin/bash

# GoEnv helper functions

install_latest_stable_go() {

    # Install `go` and add the necessary
    # configs in the local shell config file.

    local latest_version
    local current_version
    local release_list="https://golang.org/doc/devel/release.html"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check if `go` is installed

    if ! command -v "go" &>/dev/null; then
        return 1
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check if `goenv` is installed

    if ! command -v "goenv" &>/dev/null; then
        return 1
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    latest_version="$(
        curl --silent $release_list | \
        grep -E -o 'go[0-9\.]+' | \
        grep -E -o '[0-9]\.[0-9]+(\.[0-9]+)?' | \
        sort -V | \
        uniq | \
        tail -1
    )"
    current_version="$(
        go version | \
        cut -d " " -f3 | \
        sed "s/go//g"
    )"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    if ! [ -d "$HOME/.goenv/versions/$latest_version" ]; then
        if [ "$current_version" != "$latest_version" ]; then
            . "$HOME/.bashrc" \
                && goenv install "$latest_version" \
                && goenv global "$latest_version"
        fi
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "------------------------------"
echo "Running go module"
echo "------------------------------"
echo ""

# Install `brew` dependencies

echo "------------------------------"
echo "Installing brew dependencies"

brew bundle install -v --file="./brewfile"

# Initialize `goenv`

echo "------------------------------"
goenv init

if [[ -z "${SMU_FISH_DIR+x}" ]]; then
    echo "It looks like you are not using the set-me-up terminal module."
    echo "Please follow the goenv instructions above (generated by the command 'goenv init') to complete the installation."
    read -n 1 -s -r -p "Press any key to continue."
    echo ""
fi

# Install the latest Go version using `goenv`

echo "------------------------------"
echo "Installing the latest version of go"

install_latest_stable_go

goenv rehash
