#!/bin/bash

# shellcheck source=/dev/null

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files() {

    declare CURRENT_DIRECTORY

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    CURRENT_DIRECTORY="$(pwd)"

    declare -r -a FILES_TO_SOURCE=(
        "bash_aliases"
        "bash_autocomplete"
        "bash_exports"
        "bash_functions"
        "bash_options"
        "bash_prompt"
        "keybindings"
        "bash.local"  # For local settings that should
                      # not be under version control.
    )

    local file=""
    local i=""

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    for i in ${!FILES_TO_SOURCE[*]}; do

        file="$HOME/.${FILES_TO_SOURCE[$i]}"

        [ -r "$file" ] \
            && . "$file"

    done

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    . "$DOTFILES/.dotfiles/utilities/utils.sh"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    cd "$CURRENT_DIRECTORY" || return

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

source_bash_files
unset -f source_bash_files

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# load bash-sensible configs.
# see: https://github.com/mrzool/bash-sensible

if [ -d "$HOME"/.config/bash-sensible ]; then
    . "$HOME"/.config/bash-sensible/sensible.bash
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Clear system messages (system copyright notice, the date
# and time of the last login, the message of the day, etc.)
# and changes directory to $HOME.

clear && cd "$HOME" || return

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Always start tmux on start-up of bash
# see: https://unix.stackexchange.com/a/219803/173825

if command -v tmux >/dev/null; then
        if [ -n "$PS1" ]; then # unless shell is not loaded interactively, run `tmux`
                [[ ! $TERM =~ screen ]] && [ -z "$TMUX" ] && tmux
        fi
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Start up fish shell

command -v fish && fish

