#!/bin/bash

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create data URI from a file.

datauri() {

    local mimeType=""

    if [ -f "$1" ]; then
        mimeType=$(file -b --mime-type "$1")
        #                └─ do not prepend the FILE to the output

        if [[ $mimeType == text/* ]]; then
            mimeType="$mimeType;charset=utf-8"
        fi

        printf "data:%s;base64,%s" \
                    "$mimeType" \
                    "$(openssl base64 -in "$1" | tr -d "\n")"
    else
        printf "%s is not a file.\n" "$1"
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Delete files that match a certain pattern from the current directory.

delete_files() {
    local q="${1:-*.DS_Store}"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    find . -type f -name "$q" -ls -delete
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get gzip information (gzipped file size + reduction size).

gz() {

    declare -i GZIPPED_SIZE=0
    declare -i ORIGINAL_SIZE=0

    if [ -f "$1" ]; then
        if [ -s "$1" ]; then

            ORIGINAL_SIZE=$( wc -c < "$1" )
            printf "\n original size:   %12s\n" "$(hrfs "$ORIGINAL_SIZE")"

            GZIPPED_SIZE=$( gzip -c "$1" | wc -c )
            printf " gzipped size:    %12s\n" "$(hrfs "$GZIPPED_SIZE")"

            printf " ─────────────────────────────\n"
            printf " reduction:       %12s [%s%%]\n\n" \
                        "$( hrfs $((ORIGINAL_SIZE - GZIPPED_SIZE)) )" \
                        "$( printf "%s" "$ORIGINAL_SIZE $GZIPPED_SIZE" | \
                            awk '{ printf "%.1f", 100 - $2 * 100 / $1 }' | \
                            sed -e "s/0*$//;s/\.$//" )"
                            #              └─ remove tailing zeros

        else
            printf "\"%s\" is empty.\n" "$1"
        fi
    else
        printf "\"%s\" is not a file.\n" "$1"
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Human readable file size
# (because `du -h` doesn't cut it for me).

hrfs() {

    printf "%s" "$1" |
    awk '{
            i = 1;
            split("B KB MB GB TB PB EB ZB YB WTFB", v);
            value = $1;

            # confirm that the input is a number
            if ( value + .0 == value ) {

                while ( value >= 1024 ) {
                    value/=1024;
                    i++;
                }

                if ( value == int(value) ) {
                    printf "%d %s", value, v[i]
                } else {
                    printf "%.1f %s", value, v[i]
                }

            }
        }' |
    sed -e ":l" \
        -e "s/\([0-9]\)\([0-9]\{3\}\)/\1,\2/; t l"
    #    └─ add thousands separator
    #       (changes "1023.2 KB" to "1,023.2 KB")
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Create new directories and enter the first one.

mkd() {
    if [ -n "$*" ]; then

        mkdir -p "$@"
        #      └─ make parent directories if needed

        cd "$@" \
            || exit 1

    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Search history.

qh() {
    #           ┌─ enable colors for pipe
    #           │  ("--color=auto" enables colors only if
    #           │  the output is in the terminal)
    grep --color=always "$*" "$HISTFILE" |       less -RX
    # display ANSI color escape sequences in raw form ─┘│
    #       don't clear the screen after quitting less ─┘
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Search for text within the current directory.

qt() {
    grep -ir --color=always "$*" --exclude-dir=".git" --exclude-dir="node_modules" . | less -RX
    #     │└─ search all files under each directory, recursively
    #     └─ ignore case
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# extract any type of compressed file
function extract {
    echo Extracting "$1" ...
    if [ -f "$1" ] ; then
        case "$1" in
            *.tar.bz2)   tar xjf "$1"  ;;
            *.tar.gz)    tar xzf "$1"  ;;
            *.bz2)       bunzip2 "$1"  ;;
            *.rar)       rar x "$1"    ;;
            *.gz)        gunzip "$1"   ;;
            *.tar)       tar xf "$1"  ;;
            *.tbz2)      tar xjf "$1"  ;;
            *.tgz)       tar xzf "$1"  ;;
            *.zip)       unzip "$1"   ;;
            *.Z)         uncompress "$1"  ;;
            *.7z)        7z x "$1"  ;;
            *)        echo "'$1' cannot be extracted via extract()" ;;
        esac
    else
        echo "'$1' is not a valid file"
    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# check if a certain process is running
function is_running {
    declare -r PROCESS="$1"

    if pgrep -f "$PROCESS" > /dev/null; then
        echo "($PROCESS) is running"
    else
        echo "($PROCESS)" "is not running."
    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# ghf - [G]rep [H]istory [F]or top ten commands and execute one
# usage:
#  Most frequent command in recent history
#   ghf
#  Most frequent instances of {command} in all history
#   ghf {command}
#  Execute {command-number} after a call to ghf
#   !! {command-number}
function latest-history { history | tail -n 50 ; }
function grepped-history { history | grep "$1" ; }
function chop-first-column { awk '{for (i=2; i<NF; i++) printf $i " "; print $NF}' ; }
function add-line-numbers { awk '{print NR " " $0}' ; }
function top-ten { sort | uniq -c | sort -r | head -n 10 ; }
function unique-history { chop-first-column | top-ten | chop-first-column | add-line-numbers ; }
function ghf {
  if [ $# -eq 0 ]; then latest-history | unique-history; fi
  if [ $# -eq 1 ]; then grepped-history "$1" | unique-history; fi
  if [ $# -eq 2 ]; then
    grepped-history "$1" | unique-history | grep ^"$2" | chop-first-column;
  fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# piknik - Copy/paste anything over the network!
# see: https://github.com/jedisct1/piknik#suggested-shell-aliases

# pko <content> : copy <content> to the clipboard
pko() {
    if command -v "piknik" &> /dev/null; then
        echo "$*" | piknik -copy
    else
        echo "(piknik) is not installed"
    fi
}

# pkf <file> : copy the content of <file> to the clipboard
pkf() {
    if command -v "piknik" &> /dev/null; then
        piknik -copy < "$1"
    else
        echo "(piknik) is not installed"
    fi
}

# pkfr [<dir>] : send a whole directory to the clipboard, as a tar archive
pkfr() {
    if command -v "piknik" &> /dev/null; then
        tar czpvf - "${1:-.}" | piknik -copy
    else
        echo "(piknik) is not installed"
    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# transfer.sh - Easy file sharing from the command line.
# see: https://transfer.sh/

transfer() {
    if [ $# -eq 0 ]; then
        echo -e "No arguments specified. Usage:\necho transfer /tmp/test.md\ncat /tmp/test.md | transfer test.md";
        return 1;
    fi

    tmpfile=$( mktemp -t transferXXX );

    if tty -s; then
        basefile=$(basename "$1" | sed -e 's/[^a-zA-Z0-9._-]/-/g');
        curl --progress-bar --upload-file "$1" "https://transfer.sh/$basefile" >> "$tmpfile";
    else
        curl --progress-bar --upload-file "-" "https://transfer.sh/$1" >> "$tmpfile" ;
    fi;

    cat "$tmpfile";

    rm -f "$tmpfile";

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Vim functions

# Bash: Kill Vim when “Vim: Warning: Output not to a terminal”
# see: https://stackoverflow.com/a/46432233/5290011
vim() {
  [ -t 1 ] && \
    command vim "$@"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Process phone images.

ppi() {
    command -v "convert" &> /dev/null \
        || exit 0;

    declare query="${1:-*.jpg}"
    declare geometry="${2:-50%}"

    for i in $query; do

        if [[ "$(echo "${i##*.}" | tr '[:upper:]' '[:lower:]')" != "png" ]]; then
            imgName="${i%.*}.png"
        else
            imgName="_${i%.*}.png"
        fi

        convert "$i" \
            -colorspace RGB \
            +sigmoidal-contrast 11.6933 \
            -define filter:filter=Sinc \
            -define filter:window=Jinc \
            -define filter:lobes=3 \
            -sigmoidal-contrast 11.6933 \
            -colorspace sRGB \
            -background transparent \
            -gravity center \
            -resize "$geometry" \
            +append \
            "$imgName" \
        && printf "* %s (%s)\n" \
            "$imgName" \
            "$geometry"

    done
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update dotfiles

function du() {
    if [ -d "$DOTFILES" ]; then
        bash "$DOTFILES"/smu --selfupdate
    else
        echo "($DOTFILES) does not exist"
    fi
}

function fdu() {
    source <(curl -s "https://raw.githubusercontent.com/nicholasadamou/utilities/master/utilities.sh")

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    os="$(get_os)"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    if [ "$os" == "macos" ]; then
        os='master'
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    if [ -d "$DOTFILES" ]; then
        sudo rm -rf "$DOTFILES" && \
            bash <(curl -s -L https://raw.githubusercontent.com/nicholasadamou/dotfiles/"${os}"/.dotfiles/modules/install.sh) && \
            bash "$DOTFILES"/smu --rcup && \
            . "$HOME"/.bash_profile
    else
        echo "($DOTFILES) does not exist"
    fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Updates MacOS apps, brew, npm, fish, fisher, omf, pip, pip3 and their installed packages

function u() {
    sudo softwareupdate --install --all

    if command -v "mas" &> /dev/null; then
        mas upgrade
    fi

    if command -v "brew" &> /dev/null; then
        brew update
        brew upgrade
        brew cu --all --yes --cleanup --quiet
    fi

    if command -v "basher" &> /dev/null; then
        basher update
    fi

	if command -v "fish" &> /dev/null; then
		fish -c "type -q fisher && \
			fisher && \
			fisher self-update"

		fish -c "type -q omf && \
			omf update"

		fish -c "fish_update_completions"
	fi

    if command -v "npm" &> /dev/null; then
        sudo npm i -g npm@latest

        if command -v "npm-check" &> /dev/null; then
            npm-check --global --update-all
        fi
    fi

    if command -v "pip3" &> /dev/null; then
        pip3 install -U pip
    fi

    if command -v "pip" &> /dev/null; then
        pip install --quiet --user --upgrade pip
        pip install --quiet --user --upgrade setuptools

		if command -v "pip-review" &> /dev/null; then
        	pip-review -a
    	fi
    fi

    if [ -d "$HOME/.vim/plugins/Vundle.vim" ]; then
        vim +PluginUpdate +qall
    fi
}

