#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias m="man"
alias map="xargs -n1"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias rm="rm -i -rf --"
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# 'ls' aliases

alias ls="exa"

# List all files colorized in long format
alias l="exa -l"
# List only directories
alias lsd="ls -lF --color | grep --color=never '^d'"
# List only hidden files
alias lsh="ls -ld .?*"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# dotfiles alias

alias du="git -C \$DOTFILES pull \
           && git -C \$DOTFILES submodule update --quiet --init --recursive \
           && git -C \$DOTFILES submodule foreach git pull"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shortcuts

alias dev="cd \$HOME/dev"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Get local IP.

alias local-ip="ifconfig \
                    | grep 'inet addr' \
                    | grep -v '127.0.0.1' \
                    | cut -d: -f2 \
                    | cut -d' ' -f1"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# `git` aliases

alias git=hub
alias acp="git add -A && git commit -v && git push"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# `lazygit` aliases

alias lg="lazygit"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# `wttr` alias

alias wttr="curl wttr.in"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# thefuck - Magnificent app which corrects your previous console command.
# see: https://github.com/nvbn/thefuck/wiki/Shell-aliases#bash
eval "$(thefuck --alias)"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Node Package Manager`

# alias n="npm" # Do not use if using 'n' for Node version control
alias npmi='npm i -g'
alias npmr='npm uninstall -g'
alias npmls='npm list -g --depth 0'
alias npms='npm s'
alias npmu='npm i -g npm@latest'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `Yarn Package Manager`

alias yr='yarn remove'
alias ya='yarn add'
alias yu='yarn self-update && yarn upgrade && yarn upgrade-interactive'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for `Homebrew`

alias brewi='brew install'
alias brewr='brew uninstall'
alias brewls='brew list'
alias brews='brew search'
alias brewu='brew update && brew upgrade && brew cu --all --yes --cleanup --quiet'
alias brewd='brew doctor'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `pip`

alias pipi='pip install'
alias pipr='pip uninstall'
alias pipls='pip list'
alias pips='pip search'
alias pipu="sudo pip install --upgrade pip \
                && sudo pip install --upgrade setuptools \
                && sudo pip-review --auto"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for the `pip3`

alias pip3i='pip3 install'
alias pip3r='pip3 uninstall'
alias pip3ls='pip3 list'
alias pip3s='pip3 search'
alias pip3u="sudo pip3 install -U pip \
                && sudo -H pip3 install -U pip \
                && sudo pip-review --auto"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Shorter commands for `Composer`

alias ci='composer install'
alias cr='composer remove'
alias cls='composer list'
alias cs='composer search'
alias cu='composer self-update'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Update applications and CLTs.

alias u="sudo softwareupdate --install --all \
            && mas upgrade \
            && brew update && brew upgrade && brew cu --all --yes --cleanup --quiet \
            && basher update \
            && sudo \"\$(which npm)\" i -g npm@latest \
            && npm-check --global --update-all \
            && sudo pip3 install -U pip \
            && sudo -H pip3 install -U pip \
            && sudo pip-review --auto \
            && sudo pip install --upgrade pip \
            && sudo pip install --upgrade setuptools \
            && sudo pip-review --auto \
            && vim +PluginUpdate +qall"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# piknik - Copy/paste anything over the network!
# see: https://github.com/jedisct1/piknik#suggested-shell-aliases

# pkc : read the content to copy to the clipboard from STDIN
alias pkc='piknik -copy'

# pkp : paste the clipboard content
alias pkp='piknik -paste'

# pkm : move the clipboard content
alias pkm='piknik -move'

# pkz : delete the clipboard content
alias pkz='piknik -copy < /dev/null'

# pkpr : extract clipboard content sent using the pkfr command
alias pkpr='piknik -paste | tar xzhpvf -'
