#!/bin/bash

readonly python2=${python2:-"2.7.14"}
readonly python3=${python3:-"3.6.5"}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# PyEnv helper functions

install_latest_stable_python() {

    # Install the latest stable version of Python
    # (this will also set it as the default).

    # Determine which version is the LTS version of Python
    # see: https://stackoverflow.com/a/33423958/5290011

    # Determine the current version of Python installed
    # see: https://stackoverflow.com/a/30261215/5290011

    local latest_version
    local current_version

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    # Check if `pyenv` is installed

    if ! command -v "pyenv" &>/dev/null; then
        return 1
    fi

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    latest_version="$(
        pyenv install --list | \
        grep -v - | \
        grep -v b | \
        tail -1 | \
        tr -d '[:space:]'
    )"
    current_version="$(
        python -V 2>&1 | cut -d " " -f2
    )"

    # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    if [ "$current_version" != "$latest_version" ]; then
        pyenv install $latest_version \
            && pyenv global $latest_version
    fi

}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

echo "------------------------------"
echo "Running python module"
echo "------------------------------"
echo ""

# Install `brew` dependencies

echo "------------------------------"
echo "Installing brew dependencies"

brew bundle install -v --file="./brewfile"

# Initialize `pyenv`

echo "------------------------------"
pyenv init

if [[ -z "${SMU_FISH_DIR+x}" ]]; then
    echo "It looks like you are not using the set-me-up terminal module."
    echo "Please follow the pyenv instructions above (generated by the command 'pyenv init') to complete the installation."
    read -n 1 -s -r -p "Press any key to continue."
    echo ""
fi

# Install the latest Python version using `pyenv`

echo "------------------------------"
echo "Installing the latest version of python"

install_latest_stable_python

pyenv rehash

# Install pip packages

echo "------------------------------"
echo "Installing pip packages"

pip install --quiet \
cheat \
pip-review

# Install pip3 packages

echo "------------------------------"
echo "Installing pip3 packages"

pip3 install --quiet \
thefuck \
pip-review